[project]
name = "symplearn"
dynamic = ["version"]
description = "Learning non-canonical Hamiltonian dynamics"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
where = ["src/"]